service: lambda-sqs-consumer

frameworkVersion: '2'

custom:
  myStage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: python3.8
  stage: dev
  memorySize: 128
  timeout: 30

functions:
  consumerSQS:
    handler: handler.handler
    events:
      - sqs: "arn:aws:sqs:us-east-1:734443076237:sqs-principal-${self:custom.myStage}"
      