service: lambda-sns-producer

frameworkVersion: '2'

custom:
  myStage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: python3.8
  stage: dev
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "arn:aws:sns:us-east-1:*:sns-email-topic-${self:custom.myStage}"
  environment:
    sns_arn: "arn:aws:sns:us-east-1:734443076237:sns-email-topic-${self:custom.myStage}"
  
functions:
  producerSNS:
    handler: handler.handler
    events:
      - sqs: "arn:aws:sqs:us-east-1:734443076237:sqs-secundaria-${self:custom.myStage}"
      